apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: producer
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVER_ADDRESS
              value: "kafka-service:29093"