apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-test-web-app-deployment
  labels:
    app: kafka-test-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-test-web-app
  template:
    metadata:
      labels:
        app: kafka-test-web-app
    spec:
      containers:
        - name: kafka-test-web-app
          image: kafka-test-web-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080